#!/bin/bash
count=5
[[ $count -eq 5 ]] && echo "Equal to 5"
[[ $count -gt 3 ]] && echo "Greater than 3"
[[ $count -lt 10 ]]  && echo "Less than 10" 

#
## For numeric comparisons, use different operatos
# -ne --> Not Equal
# =eq --> Equal
# -gt --> Greater than
# -lt --> less than 
#
## Arithmetic (( )) for Numbers

count=7
if ((count > 5 )); then
	echo "Count is greater than 5"
fi

#
## Inside (( )) use <, >, ==
## No $ needed for variables
#
